### ISSUE TITLE
Trouble building libnat

### ISSUE THREAD

**Issue by xiaoshengjun** [pytorch/fairseq#1346]
Hi, when I trained a new Levenshtein Transformer in my datasets, and it was processed by process.py by '--joined-dictionary', It will show this error, and I trained the model in two gpus.  Could you help me find the reasons, thanks very much.
 
File "train.py", line 343, in <module>
    cli_main()
  File "train.py", line 335, in cli_main
    nprocs=args.distributed_world_size,
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 1 terminated with signal SIGSEGV

And when I trained the model in 3 gpus, the error is :

170848, 512Traceback (most recent call last):
  File "train.py", line 343, in <module>
    cli_main()
  File "train.py", line 335, in cli_main
    nprocs=args.distributed_world_size,
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 2 terminated with signal SIGSEGV
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/len_transform/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/root/anaconda3/envs/len_transform/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by sdll** [comment]
Similar issues:

- https://github.com/pytorch/fairseq/issues/1308
- https://github.com/pytorch/fairseq/issues/1305

**Comment by xiaoshengjun** [comment]
Oh, thank you.

> Similar issues:
> 
> * #1308
> * #1305

**Comment by xiaoshengjun** [comment]
hi, @sdll , the issues #1308  and #1305  do not solve the problem.

**Comment by myleott** [comment]
This should be fixed now, can you please try again?

**Comment by xiaoshengjun** [comment]
> This should be fixed now, can you please try again?

hi, thanks for you replay， and I download the latest version of fairseq， and processed the data ‘--joined-dictionary’， but when I trained a new model， the problem is：

Traceback (most recent call last):
  File "train.py", line 337, in <module>
    cli_main()
  File "train.py", line 329, in cli_main
    nprocs=args.distributed_world_size,
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/anaconda3/envs/len_transform/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 3 terminated with signal SIGSEGV

could you help me？

**Comment by MultiPath** [comment]
seems to be a multi-gpu error? Can you try running on single GPU?

**Comment by xiaoshengjun** [comment]
> seems to be a multi-gpu error? Can you try running on single GPU for debugging?

hi， I have used in single GPU， when the model loaded the trained data， the code is over, but it does not show anything, and I can the GPU is not used.

**Comment by MultiPath** [comment]
> > seems to be a multi-gpu error? Can you try running on single GPU for debugging?
> 
> hi， I have used in single GPU， when the model loaded the trained data， the code is over, but it does not show anything, and I can the GPU is not used.

@xiaoshengjun  just following up. Is the problem still there in the recent refactored codebase?

**Comment by gvskalyan** [comment]
@MultiPath this still occurs in recent codebase.
Even without apex. With less no of max tokens and with higher gcc version and nvcc installed.
Installed fairseq via python setup.py build_ext --inplace.
Even on single GPU, it is segmentation fault.
Please recheck.

**Comment by myleott** [comment]
I just ran the [example command in the README](https://github.com/pytorch/fairseq/tree/master/examples/nonautoregressive_translation#train-a-model) and it works fine.

Can you confirm that libnat is built properly? Please try running the following:
```bash
$ python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'
```

You should see something like: `[[[0], [0], [0], [0], [5, 6], [0, 1, 0, 0]]]`

**Comment by xiaoshengjun** [comment]
> ```shell
> python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'
> ```

Thanks for your reply, and I have run the command what you said above, and get :
>>> from fairseq import libnat
>>> print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))
Segmentation fault

so something is wrong in my environment?

**Comment by xiaoshengjun** [comment]
> > > seems to be a multi-gpu error? Can you try running on single GPU for debugging?
> > 
> > 
> > hi， I have used in single GPU， when the model loaded the trained data， the code is over, but it does not show anything, and I can the GPU is not used.
> 
> @xiaoshengjun just following up. Is the problem still there in the recent refactored codebase?

yes, I also meet the problem.

**Comment by myleott** [comment]
> so something is wrong in my environment?

Yes, libnat has not been built properly. Can you please run `python setup.py build_ext --inplace` and share the output here?

**Comment by xiaoshengjun** [comment]
> > so something is wrong in my environment?
> 
> Yes, libnat has not been built properly. Can you please run `python setup.py build_ext --inplace` and share the output here?

hi, the output is：
# python setup.py build_ext --inplace

which: no nvcc in (/root/anaconda3/envs/fq09py12/bin:/root/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/usr/bin:/usr/local/bin:/usr/libexec/git-core:/root/bin)
running build_ext
/root/anaconda3/envs/fq09py12/lib/python3.6/site-packages/torch/utils/cpp_extension.py:196: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
skipping 'fairseq/data/data_utils_fast.cpp' Cython extension (up-to-date)
skipping 'fairseq/data/token_block_utils_fast.cpp' Cython extension (up-to-date)
copying build/lib.linux-x86_64-3.6/fairseq/libbleu.cpython-36m-x86_64-linux-gnu.so -> fairseq
copying build/lib.linux-x86_64-3.6/fairseq/data/data_utils_fast.cpython-36m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.6/fairseq/data/token_block_utils_fast.cpython-36m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.6/fairseq/libnat.cpython-36m-x86_64-linux-gnu.so -> fairseq

**Comment by myleott** [comment]
Please follow the instructions in the warning message :)

**Comment by gvskalyan** [comment]
> > so something is wrong in my environment?
> 
> Yes, libnat has not been built properly. Can you please run `python setup.py build_ext --inplace` and share the output here?

My output:
running build_ext
skipping 'fairseq/data/data_utils_fast.cpp' Cython extension (up-to-date)
skipping 'fairseq/data/token_block_utils_fast.cpp' Cython extension (up-to-date)
copying build/lib.linux-x86_64-3.7/fairseq/libbleu.cpython-37m-x86_64-linux-gnu.so -> fairseq
copying build/lib.linux-x86_64-3.7/fairseq/data/data_utils_fast.cpython-37m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.7/fairseq/data/token_block_utils_fast.cpython-37m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.7/fairseq/libnat.cpython-37m-x86_64-linux-gnu.so -> fairseq

And the snippet gives Segmentation fault

**Comment by gvskalyan** [comment]
Steps ::
1. conda create -n nat python=3.7 &&  conda activate nat
2. git clone https://github.com/pytorch/fairseq.git  &&  cd fairseq 
3.  conda install -c psi4 gcc-5
4. conda install libgcc -y
5. pip install torch && pip install cython
6. python setup.py build_ext
7. python setup.py install --user

**Comment by myleott** [comment]
Can you install gcc from the main channel instead? Something like:
```
conda install gcc_linux-64 gxx_linux-64
```
There should be versions for other platforms/architectures too.

**Comment by xiaoshengjun** [comment]
> Please follow the instructions in the warning message :)

The problem has been solved after I update the version of gcc, thanks.

**Comment by gvskalyan** [comment]
> Can you install gcc from the main channel instead? Something like:
> 
> ```
> conda install gcc_linux-64 gxx_linux-64
> ```
> 
> There should be versions for other platforms/architectures too.
> 
> Here's what I just ran and it works as expected:
> 
>     1. conda create -n nat python=3.7 && conda activate nat
> 
>     2. git clone https://github.com/pytorch/fairseq.git && cd fairseq
> 
>     3. conda install gcc_linux-64 gxx_linux-64
> 
>     4. pip install torch && pip install cython
> 
>     5. python setup.py build_ext --inplace
> 
>     6. python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'

Solved Thanks.

**Comment by gvskalyan** [comment]
@myleott when I run scaling-nmt translation example, https://github.com/pytorch/fairseq/blame/master/examples/scaling_nmt/README.md#L40 in the above conda environment along with --encoder-layerdrop 0.2 the gpu utilisation amounts to 100 and training does not start and is stuck but with the --ddp-backend no_c10d it is working fine.
Whereas without --encoder/decoder-layerdrop it works with/without ddp-backend.
Is this intended behaviour?

**Comment by myleott** [comment]
Yes, no_c10d is required when some of the model parameters are not used in the forward pass, as is the case with LayerDrop.

**Comment by luofuli** [comment]
> Can you install gcc from the main channel instead? Something like:
> 
> ```
> conda install gcc_linux-64 gxx_linux-64
> ```
> 
> There should be versions for other platforms/architectures too.
> 
> Here's what I just ran and it works as expected:
> 
> 1. conda create -n nat python=3.7 && conda activate nat
> 2. git clone https://github.com/pytorch/fairseq.git && cd fairseq
> 3. conda install gcc_linux-64 gxx_linux-64
> 4. pip install torch && pip install cython
> 5. python setup.py build_ext --inplace
> 6. python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'

great! It works!!!!!!!!

**Comment by KinWaiCheuk** [comment]
> Can you install gcc from the main channel instead? Something like:
> 
> ```
> conda install gcc_linux-64 gxx_linux-64
> ```
> 
> There should be versions for other platforms/architectures too.
> 
> Here's what I just ran and it works as expected:
> 
> 1. conda create -n nat python=3.7 && conda activate nat
> 2. git clone https://github.com/pytorch/fairseq.git && cd fairseq
> 3. conda install gcc_linux-64 gxx_linux-64
> 4. pip install torch && pip install cython
> 5. python setup.py build_ext --inplace
> 6. python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'

For me, after step 4, when I try to run step 5, I get

/opt/conda/envs/nat/lib/python3.7/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at  /pytorch/to
rch/csrc/utils/tensor_numpy.cpp:67.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
running build_ext                 
Traceback (most recent call last):
  File "/workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray                                           
  File "/workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides                                                                                                                                                                              
  File "/workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (               
ImportError: /workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 268, in <module>
    do_setup(package_data)
  File "setup.py", line 241, in do_setup
    zip_safe=False,
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/envs/nat/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/envs/nat/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/nat/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/envs/nat/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/opt/conda/envs/nat/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 265, in cython_sources
    extension.include_dirs = list(extension.include_dirs)
  File "setup.py", line 62, in include_dirs
    import numpy
  File "/workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/opt/conda/envs/nat/bin/python"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /workspace/public_data/raven/fairseq/.eggs/numpy-1.21.1-py3.7-linux-x86_64.egg/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object

**Comment by KinWaiCheuk** [comment]
> > Can you install gcc from the main channel instead? Something like:
> > ```
> > conda install gcc_linux-64 gxx_linux-64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There should be versions for other platforms/architectures too.
> > Here's what I just ran and it works as expected:
> > 
> > 1. conda create -n nat python=3.7 && conda activate nat
> > 2. git clone https://github.com/pytorch/fairseq.git && cd fairseq
> > 3. conda install gcc_linux-64 gxx_linux-64
> > 4. pip install torch && pip install cython
> > 5. python setup.py build_ext --inplace
> > 6. python -c 'from fairseq import libnat; print(libnat.suggested_ed2_path([[1, 2, 3, 4]], [[1, 3, 4, 5, 6]], 0))'
> 
> For me, after finishing step 1-5, I get the following error at step 6.
> 
> _Traceback (most recent call last): File "", line 1, in ImportError: /workspace/public_data/raven/fairseq/fairseq/libnat.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object_

I have figured out the solution. It is due to the permission problem of a mounted disk. If my git clone the fairseq repo inside the mounted disk, and do `pip install --editable ./`, then I will get the above mentioned error.

If I git clone the repo inside my system disk and do `pip install --editable ./`, this error is gone.

So there is some problem with the mounted disk. Now I am trying to follow this instruction to see if it works.
https://stackoverflow.com/a/64110234/9793316
